import { CurriculumWeek } from '@/types/curriculum';

export const curriculumData: CurriculumWeek[] = [
  // A1 Level - Week 1
  {
    id: 'A1-W1',
    level: 'A1',
    weekNumber: 1,
    title: '기초 인사와 자기소개',
    description: '영어로 인사하고 자신을 소개하는 방법을 배웁니다.',
    objectives: [
      '기본 인사 표현 익히기',
      '자기소개 문장 만들기',
      '간단한 질문에 답하기',
      '알파벳과 기본 발음 익히기',
    ],
    estimatedTime: 180, // 3시간
    order: 1,
    activities: [
      {
        id: 'A1-W1-A1',
        type: 'vocabulary',
        title: '인사 표현 익히기',
        description:
          'Hello, Hi, Good morning, Good afternoon 등 기본 인사 표현을 학습합니다.',
        duration: 20,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['greetings', 'basics'],
      },
      {
        id: 'A1-W1-A2',
        type: 'listening',
        title: '인사 듣기 연습',
        description: '원어민의 인사 표현을 듣고 따라 말해봅니다.',
        duration: 25,
        difficulty: 1,
        order: 2,
        requiredForCompletion: true,
        tags: ['greetings', 'listening'],
      },
      {
        id: 'A1-W1-A3',
        type: 'speaking',
        title: '인사 말하기 연습',
        description: '다양한 상황에서 적절한 인사를 해봅니다.',
        duration: 30,
        difficulty: 1,
        order: 3,
        requiredForCompletion: true,
        tags: ['greetings', 'speaking'],
      },
      {
        id: 'A1-W1-A4',
        type: 'grammar',
        title: '자기소개 문장 구조',
        description: 'My name is..., I am... 등 자기소개 문장 구조를 학습합니다.',
        duration: 30,
        difficulty: 1,
        order: 4,
        requiredForCompletion: true,
        tags: ['introduction', 'grammar'],
      },
      {
        id: 'A1-W1-A5',
        type: 'writing',
        title: '자기소개 글 쓰기',
        description: '배운 표현을 활용해 자기소개 글을 작성합니다.',
        duration: 35,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['introduction', 'writing'],
      },
      {
        id: 'A1-W1-A6',
        type: 'reading',
        title: '자기소개 예시 읽기',
        description: '다양한 사람들의 자기소개 글을 읽고 이해합니다.',
        duration: 25,
        difficulty: 1,
        order: 6,
        requiredForCompletion: false,
        tags: ['introduction', 'reading'],
      },
      {
        id: 'A1-W1-A7',
        type: 'vocabulary',
        title: '알파벳 복습',
        description: '영어 알파벳 26자와 발음을 복습합니다.',
        duration: 15,
        difficulty: 1,
        order: 7,
        requiredForCompletion: false,
        tags: ['alphabet', 'pronunciation'],
      },
    ],
  },

  // A1 Level - Week 2
  {
    id: 'A1-W2',
    level: 'A1',
    weekNumber: 2,
    title: '숫자와 시간 표현',
    description: '숫자를 읽고 시간을 표현하는 방법을 배웁니다.',
    objectives: [
      '1부터 100까지 숫자 익히기',
      '시간 묻고 답하기',
      '날짜와 요일 표현하기',
      '기본 수량 표현 익히기',
    ],
    estimatedTime: 195, // 3시간 15분
    order: 2,
    activities: [
      {
        id: 'A1-W2-A1',
        type: 'vocabulary',
        title: '숫자 1-20 익히기',
        description: '1부터 20까지 숫자를 영어로 읽고 씁니다.',
        duration: 20,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['numbers', 'basics'],
      },
      {
        id: 'A1-W2-A2',
        type: 'vocabulary',
        title: '숫자 20-100 익히기',
        description: '20부터 100까지 숫자를 영어로 읽고 씁니다.',
        duration: 25,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['numbers'],
      },
      {
        id: 'A1-W2-A3',
        type: 'listening',
        title: '숫자 듣기 연습',
        description: '원어민이 말하는 숫자를 듣고 받아쓰기 합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['numbers', 'listening'],
      },
      {
        id: 'A1-W2-A4',
        type: 'grammar',
        title: '시간 표현 문법',
        description: "What time is it? It's... o'clock 등 시간 표현을 학습합니다.",
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['time', 'grammar'],
      },
      {
        id: 'A1-W2-A5',
        type: 'speaking',
        title: '시간 말하기 연습',
        description: '다양한 시간을 영어로 말하는 연습을 합니다.',
        duration: 25,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['time', 'speaking'],
      },
      {
        id: 'A1-W2-A6',
        type: 'vocabulary',
        title: '요일과 날짜',
        description: '요일 이름과 날짜 표현을 학습합니다.',
        duration: 25,
        difficulty: 1,
        order: 6,
        requiredForCompletion: true,
        tags: ['date', 'vocabulary'],
      },
      {
        id: 'A1-W2-A7',
        type: 'writing',
        title: '일정표 작성하기',
        description: '요일과 시간을 사용해 간단한 일정표를 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['date', 'time', 'writing'],
      },
      {
        id: 'A1-W2-A8',
        type: 'reading',
        title: '시간표 읽기',
        description: '학교 시간표나 버스 시간표를 읽고 이해합니다.',
        duration: 10,
        difficulty: 1,
        order: 8,
        requiredForCompletion: false,
        tags: ['time', 'reading'],
      },
    ],
  },

  // A1 Level - Week 3
  {
    id: 'A1-W3',
    level: 'A1',
    weekNumber: 3,
    title: '가족과 친구 소개하기',
    description: '가족 구성원과 친구들을 소개하는 방법을 배웁니다.',
    objectives: [
      '가족 관계 표현 익히기',
      '사람 묘사하기',
      '소유격 사용하기',
      '간단한 질문과 답변하기',
    ],
    estimatedTime: 190,
    order: 3,
    activities: [
      {
        id: 'A1-W3-A1',
        type: 'vocabulary',
        title: '가족 관계 단어',
        description: 'mother, father, sister, brother 등 가족 관계 단어를 학습합니다.',
        duration: 25,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['family', 'vocabulary'],
      },
      {
        id: 'A1-W3-A2',
        type: 'grammar',
        title: '소유격 문법',
        description: "my, your, his, her 등 소유격과 's 사용법을 학습합니다.",
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['grammar', 'possessive'],
      },
      {
        id: 'A1-W3-A3',
        type: 'reading',
        title: '가족 소개 글 읽기',
        description: '다양한 가족 소개 글을 읽고 이해합니다.',
        duration: 25,
        difficulty: 1,
        order: 3,
        requiredForCompletion: true,
        tags: ['family', 'reading'],
      },
      {
        id: 'A1-W3-A4',
        type: 'speaking',
        title: '가족 소개하기',
        description: '자신의 가족 구성원을 영어로 소개합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['family', 'speaking'],
      },
      {
        id: 'A1-W3-A5',
        type: 'vocabulary',
        title: '외모와 성격 표현',
        description: 'tall, short, kind, funny 등 사람을 묘사하는 단어를 학습합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['description', 'vocabulary'],
      },
      {
        id: 'A1-W3-A6',
        type: 'writing',
        title: '친구 소개 글 쓰기',
        description: '친구의 외모와 성격을 묘사하는 글을 작성합니다.',
        duration: 35,
        difficulty: 2,
        order: 6,
        requiredForCompletion: true,
        tags: ['description', 'writing'],
      },
      {
        id: 'A1-W3-A7',
        type: 'listening',
        title: '가족 대화 듣기',
        description: '가족에 대한 대화를 듣고 이해합니다.',
        duration: 15,
        difficulty: 1,
        order: 7,
        requiredForCompletion: false,
        tags: ['family', 'listening'],
      },
    ],
  },

  // A1 Level - Week 4
  {
    id: 'A1-W4',
    level: 'A1',
    weekNumber: 4,
    title: '일상생활과 취미',
    description: '일상 활동과 취미에 대해 이야기하는 방법을 배웁니다.',
    objectives: [
      '일상 활동 동사 익히기',
      '현재 시제 사용하기',
      '취미와 좋아하는 것 표현하기',
      '빈도 부사 사용하기',
    ],
    estimatedTime: 200,
    order: 4,
    activities: [
      {
        id: 'A1-W4-A1',
        type: 'vocabulary',
        title: '일상 활동 동사',
        description: 'wake up, eat, study, sleep 등 일상 활동 동사를 학습합니다.',
        duration: 25,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['daily', 'verbs'],
      },
      {
        id: 'A1-W4-A2',
        type: 'grammar',
        title: '현재 시제 문법',
        description: '현재 시제 동사 활용과 3인칭 단수 -s를 학습합니다.',
        duration: 35,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['grammar', 'present-tense'],
      },
      {
        id: 'A1-W4-A3',
        type: 'writing',
        title: '하루 일과 쓰기',
        description: '자신의 하루 일과를 시간 순서대로 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['daily', 'writing'],
      },
      {
        id: 'A1-W4-A4',
        type: 'vocabulary',
        title: '취미 관련 단어',
        description: 'reading, swimming, playing 등 취미 관련 단어를 학습합니다.',
        duration: 20,
        difficulty: 1,
        order: 4,
        requiredForCompletion: true,
        tags: ['hobbies', 'vocabulary'],
      },
      {
        id: 'A1-W4-A5',
        type: 'grammar',
        title: '좋아하는 것 표현하기',
        description: 'like, love, enjoy + -ing 형태를 학습합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['grammar', 'preferences'],
      },
      {
        id: 'A1-W4-A6',
        type: 'listening',
        title: '취미 대화 듣기',
        description: '사람들이 취미에 대해 이야기하는 것을 듣습니다.',
        duration: 25,
        difficulty: 2,
        order: 6,
        requiredForCompletion: true,
        tags: ['hobbies', 'listening'],
      },
      {
        id: 'A1-W4-A7',
        type: 'speaking',
        title: '취미 말하기 연습',
        description: '자신의 취미와 좋아하는 활동에 대해 말합니다.',
        duration: 25,
        difficulty: 2,
        order: 7,
        requiredForCompletion: true,
        tags: ['hobbies', 'speaking'],
      },
      {
        id: 'A1-W4-A8',
        type: 'reading',
        title: '취미 소개 글 읽기',
        description: '다양한 사람들의 취미 소개 글을 읽고 이해합니다.',
        duration: 10,
        difficulty: 1,
        order: 8,
        requiredForCompletion: false,
        tags: ['hobbies', 'reading'],
      },
    ],
  },

  // A1 Level - Week 5
  {
    id: 'A1-W5',
    level: 'A1',
    weekNumber: 5,
    title: '장소와 위치 표현',
    description: '장소를 묘사하고 위치를 설명하는 방법을 배웁니다.',
    objectives: [
      '장소 관련 단어 익히기',
      '전치사 사용하기 (in, on, at, near)',
      '길 묻고 안내하기',
      'There is/are 구문 사용하기',
    ],
    estimatedTime: 185,
    order: 5,
    activities: [
      {
        id: 'A1-W5-A1',
        type: 'vocabulary',
        title: '장소 단어 익히기',
        description:
          'school, hospital, bank, restaurant 등 기본 장소 단어를 학습합니다.',
        duration: 25,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['places', 'vocabulary'],
      },
      {
        id: 'A1-W5-A2',
        type: 'grammar',
        title: '전치사 in, on, at',
        description: '위치를 나타내는 기본 전치사를 배웁니다.',
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['prepositions', 'grammar'],
      },
      {
        id: 'A1-W5-A3',
        type: 'listening',
        title: '위치 묘사 듣기',
        description: '사람들이 위치를 설명하는 대화를 듣습니다.',
        duration: 25,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['places', 'listening'],
      },
      {
        id: 'A1-W5-A4',
        type: 'grammar',
        title: 'There is/are 구문',
        description: '사물의 존재를 표현하는 There is/are를 배웁니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['grammar', 'existence'],
      },
      {
        id: 'A1-W5-A5',
        type: 'speaking',
        title: '길 묻고 안내하기',
        description: '길을 묻고 안내하는 기본 표현을 연습합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['directions', 'speaking'],
      },
      {
        id: 'A1-W5-A6',
        type: 'writing',
        title: '우리 동네 소개하기',
        description: '자신이 사는 동네의 장소들을 영어로 소개합니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['places', 'writing'],
      },
      {
        id: 'A1-W5-A7',
        type: 'reading',
        title: '지도 읽기',
        description: '간단한 지도와 설명을 읽고 이해합니다.',
        duration: 15,
        difficulty: 1,
        order: 7,
        requiredForCompletion: false,
        tags: ['places', 'reading'],
      },
    ],
  },

  // A1 Level - Week 6
  {
    id: 'A1-W6',
    level: 'A1',
    weekNumber: 6,
    title: '음식과 쇼핑',
    description: '음식을 주문하고 쇼핑하는 기본 표현을 배웁니다.',
    objectives: [
      '음식과 음료 관련 어휘 익히기',
      '식당에서 주문하기',
      '가격 묻고 답하기',
      '수량 표현하기',
    ],
    estimatedTime: 200,
    order: 6,
    activities: [
      {
        id: 'A1-W6-A1',
        type: 'vocabulary',
        title: '음식 이름 익히기',
        description:
          'apple, bread, milk, coffee 등 기본 음식 이름을 학습합니다.',
        duration: 25,
        difficulty: 1,
        order: 1,
        requiredForCompletion: true,
        tags: ['food', 'vocabulary'],
      },
      {
        id: 'A1-W6-A2',
        type: 'vocabulary',
        title: '음료와 디저트',
        description: '음료수와 디저트 이름을 영어로 배웁니다.',
        duration: 20,
        difficulty: 1,
        order: 2,
        requiredForCompletion: true,
        tags: ['food', 'drinks'],
      },
      {
        id: 'A1-W6-A3',
        type: 'listening',
        title: '식당 주문 듣기',
        description: '식당에서 주문하는 대화를 듣고 이해합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['food', 'ordering', 'listening'],
      },
      {
        id: 'A1-W6-A4',
        type: 'grammar',
        title: '수량 표현 (some, any)',
        description: 'I would like some... / Do you have any...? 를 배웁니다.',
        duration: 25,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['quantity', 'grammar'],
      },
      {
        id: 'A1-W6-A5',
        type: 'speaking',
        title: '음식 주문하기',
        description: '식당에서 음식을 주문하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['ordering', 'speaking'],
      },
      {
        id: 'A1-W6-A6',
        type: 'grammar',
        title: '가격 묻고 답하기',
        description: 'How much is...? / It\'s... dollars. 표현을 배웁니다.',
        duration: 25,
        difficulty: 2,
        order: 6,
        requiredForCompletion: true,
        tags: ['shopping', 'grammar'],
      },
      {
        id: 'A1-W6-A7',
        type: 'writing',
        title: '쇼핑 목록 만들기',
        description: '영어로 쇼핑 목록을 작성합니다.',
        duration: 20,
        difficulty: 1,
        order: 7,
        requiredForCompletion: false,
        tags: ['shopping', 'writing'],
      },
      {
        id: 'A1-W6-A8',
        type: 'reading',
        title: '메뉴판 읽기',
        description: '식당 메뉴판을 읽고 이해합니다.',
        duration: 25,
        difficulty: 2,
        order: 8,
        requiredForCompletion: false,
        tags: ['food', 'reading'],
      },
    ],
  },

  // A1 Level - Week 7
  {
    id: 'A1-W7',
    level: 'A1',
    weekNumber: 7,
    title: '과거와 미래 이야기하기',
    description: '과거의 일과 미래 계획을 영어로 표현하는 방법을 배웁니다.',
    objectives: [
      '과거 시제 기본 익히기',
      '불규칙 동사 과거형',
      '미래 표현 (will, going to)',
      '시간 표현 확장하기',
    ],
    estimatedTime: 205,
    order: 7,
    activities: [
      {
        id: 'A1-W7-A1',
        type: 'grammar',
        title: '과거 시제 기본',
        description: '규칙 동사의 과거형 (-ed)을 배웁니다.',
        duration: 30,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['past-tense', 'grammar'],
      },
      {
        id: 'A1-W7-A2',
        type: 'vocabulary',
        title: '불규칙 동사 과거형',
        description: 'go-went, eat-ate 등 기본 불규칙 동사를 학습합니다.',
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['past-tense', 'irregular-verbs'],
      },
      {
        id: 'A1-W7-A3',
        type: 'listening',
        title: '지난 주말 이야기 듣기',
        description: '사람들의 주말 활동을 과거 시제로 듣습니다.',
        duration: 25,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['past-tense', 'listening'],
      },
      {
        id: 'A1-W7-A4',
        type: 'speaking',
        title: '어제 한 일 말하기',
        description: '어제의 활동을 과거 시제로 말하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['past-tense', 'speaking'],
      },
      {
        id: 'A1-W7-A5',
        type: 'grammar',
        title: '미래 표현 will',
        description: 'I will... / I will not... 미래 표현을 배웁니다.',
        duration: 25,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['future', 'grammar'],
      },
      {
        id: 'A1-W7-A6',
        type: 'grammar',
        title: '미래 계획 be going to',
        description: 'I am going to... 계획 표현을 배웁니다.',
        duration: 25,
        difficulty: 2,
        order: 6,
        requiredForCompletion: true,
        tags: ['future', 'grammar'],
      },
      {
        id: 'A1-W7-A7',
        type: 'writing',
        title: '주말 계획 쓰기',
        description: '미래 시제로 주말 계획을 작성합니다.',
        duration: 25,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['future', 'writing'],
      },
      {
        id: 'A1-W7-A8',
        type: 'reading',
        title: '일기 읽기',
        description: '과거 시제로 쓰인 간단한 일기를 읽습니다.',
        duration: 15,
        difficulty: 1,
        order: 8,
        requiredForCompletion: false,
        tags: ['past-tense', 'reading'],
      },
    ],
  },

  // A1 Level - Week 8
  {
    id: 'A1-W8',
    level: 'A1',
    weekNumber: 8,
    title: 'A1 총정리 및 복습',
    description: 'A1 레벨에서 배운 모든 내용을 복습하고 종합 평가를 진행합니다.',
    objectives: [
      'A1 핵심 문법 복습',
      'A1 필수 어휘 총정리',
      '기본 회화 연습',
      'A1 레벨 평가 테스트',
    ],
    estimatedTime: 180,
    order: 8,
    activities: [
      {
        id: 'A1-W8-A1',
        type: 'grammar',
        title: 'A1 문법 총복습',
        description:
          'be동사, 현재/과거/미래 시제 등 A1 핵심 문법을 복습합니다.',
        duration: 40,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['review', 'grammar'],
      },
      {
        id: 'A1-W8-A2',
        type: 'vocabulary',
        title: 'A1 어휘 총정리',
        description:
          '인사, 숫자, 가족, 장소, 음식 등 A1 필수 어휘를 복습합니다.',
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['review', 'vocabulary'],
      },
      {
        id: 'A1-W8-A3',
        type: 'listening',
        title: 'A1 종합 듣기 평가',
        description: 'A1 레벨의 다양한 주제를 다룬 듣기 평가를 진행합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['review', 'listening', 'test'],
      },
      {
        id: 'A1-W8-A4',
        type: 'speaking',
        title: 'A1 말하기 종합 평가',
        description: '자기소개, 일상 대화 등 A1 회화 능력을 평가합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['review', 'speaking', 'test'],
      },
      {
        id: 'A1-W8-A5',
        type: 'reading',
        title: 'A1 독해 종합 평가',
        description: '간단한 글을 읽고 이해하는 능력을 평가합니다.',
        duration: 25,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['review', 'reading', 'test'],
      },
      {
        id: 'A1-W8-A6',
        type: 'writing',
        title: 'A1 작문 종합 평가',
        description: '간단한 자기소개 글과 일상 묘사를 작성합니다.',
        duration: 25,
        difficulty: 2,
        order: 6,
        requiredForCompletion: true,
        tags: ['review', 'writing', 'test'],
      },
    ],
  },

  // ==================== A2 레벨 ====================
  // A2 Level - Week 1
  {
    id: 'A2-W1',
    level: 'A2',
    weekNumber: 1,
    title: '여행 계획과 경험',
    description: '여행 계획을 세우고 과거 여행 경험을 이야기하는 방법을 배웁니다.',
    objectives: [
      '여행 관련 어휘 확장하기',
      '과거완료 시제 이해하기',
      '비교급과 최상급 사용하기',
      '여행 경험 서술하기',
    ],
    estimatedTime: 200,
    order: 9,
    activities: [
      {
        id: 'A2-W1-A1',
        type: 'vocabulary',
        title: '여행 준비와 교통수단',
        description: '여행 계획과 다양한 교통수단 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['travel', 'vocabulary'],
      },
      {
        id: 'A2-W1-A2',
        type: 'grammar',
        title: '과거완료 시제 (Past Perfect)',
        description: '과거보다 더 이전의 일을 표현하는 과거완료 시제를 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['past-perfect', 'grammar'],
      },
      {
        id: 'A2-W1-A3',
        type: 'listening',
        title: '공항 안내 방송 듣기',
        description: '공항에서 흔히 들을 수 있는 안내 방송을 듣고 이해합니다.',
        duration: 25,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['travel', 'listening', 'airport'],
      },
      {
        id: 'A2-W1-A4',
        type: 'grammar',
        title: '비교급과 최상급',
        description: '사물이나 장소를 비교하는 표현을 학습합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['comparison', 'grammar'],
      },
      {
        id: 'A2-W1-A5',
        type: 'speaking',
        title: '여행 계획 말하기',
        description: '자신의 여행 계획을 구체적으로 설명하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['travel', 'speaking'],
      },
      {
        id: 'A2-W1-A6',
        type: 'reading',
        title: '여행 가이드북 읽기',
        description: '간단한 여행 가이드북을 읽고 정보를 찾습니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['travel', 'reading'],
      },
      {
        id: 'A2-W1-A7',
        type: 'writing',
        title: '여행 후기 작성하기',
        description: '자신의 여행 경험을 과거 시제로 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['travel', 'writing'],
      },
    ],
  },

  // A2 Level - Week 2
  {
    id: 'A2-W2',
    level: 'A2',
    weekNumber: 2,
    title: '취미와 여가활동',
    description: '다양한 취미 활동과 여가 시간을 표현하는 방법을 배웁니다.',
    objectives: [
      '취미와 스포츠 어휘 익히기',
      '현재완료 시제 이해하기',
      '빈도 부사와 시간 표현 확장',
      '취미 활동 묘사하기',
    ],
    estimatedTime: 195,
    order: 10,
    activities: [
      {
        id: 'A2-W2-A1',
        type: 'vocabulary',
        title: '취미와 스포츠 활동',
        description: '다양한 취미와 스포츠 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['hobbies', 'sports', 'vocabulary'],
      },
      {
        id: 'A2-W2-A2',
        type: 'grammar',
        title: '현재완료 시제 (Present Perfect)',
        description: '과거부터 현재까지 이어지는 경험을 표현하는 현재완료를 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['present-perfect', 'grammar'],
      },
      {
        id: 'A2-W2-A3',
        type: 'reading',
        title: '스포츠 뉴스 기사 읽기',
        description: '간단한 스포츠 뉴스 기사를 읽고 이해합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['sports', 'reading', 'news'],
      },
      {
        id: 'A2-W2-A4',
        type: 'grammar',
        title: 'For vs Since 구분하기',
        description: '기간을 나타내는 for와 시작점을 나타내는 since를 구분합니다.',
        duration: 25,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['time', 'grammar'],
      },
      {
        id: 'A2-W2-A5',
        type: 'listening',
        title: '취미 동호회 대화 듣기',
        description: '취미 동호회에서 나누는 대화를 듣고 이해합니다.',
        duration: 25,
        difficulty: 2,
        order: 5,
        requiredForCompletion: false,
        tags: ['hobbies', 'listening'],
      },
      {
        id: 'A2-W2-A6',
        type: 'speaking',
        title: '취미 소개하기',
        description: '자신의 취미를 구체적으로 소개하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['hobbies', 'speaking'],
      },
      {
        id: 'A2-W2-A7',
        type: 'writing',
        title: '취미 블로그 글쓰기',
        description: '자신의 취미에 대한 블로그 글을 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['hobbies', 'writing'],
      },
    ],
  },

  // A2 Level - Week 3
  {
    id: 'A2-W3',
    level: 'A2',
    weekNumber: 3,
    title: '건강과 생활습관',
    description: '건강 상태를 설명하고 조언을 주고받는 방법을 배웁니다.',
    objectives: [
      '건강과 신체 부위 어휘 확장',
      '조동사 should, must, have to 사용',
      '증상 설명과 조언하기',
      '건강한 생활습관 표현하기',
    ],
    estimatedTime: 200,
    order: 11,
    activities: [
      {
        id: 'A2-W3-A1',
        type: 'vocabulary',
        title: '질병과 증상 표현',
        description: '다양한 질병과 증상을 나타내는 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['health', 'symptoms', 'vocabulary'],
      },
      {
        id: 'A2-W3-A2',
        type: 'grammar',
        title: '조동사 Should와 Must',
        description: '조언과 의무를 표현하는 조동사를 배웁니다.',
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['modals', 'grammar', 'advice'],
      },
      {
        id: 'A2-W3-A3',
        type: 'listening',
        title: '병원 진료 대화 듣기',
        description: '의사와 환자의 진료 대화를 듣고 이해합니다.',
        duration: 30,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['health', 'listening', 'doctor'],
      },
      {
        id: 'A2-W3-A4',
        type: 'grammar',
        title: 'Have to vs Must 구분',
        description: '의무를 나타내는 두 표현의 차이를 이해합니다.',
        duration: 25,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['modals', 'grammar'],
      },
      {
        id: 'A2-W3-A5',
        type: 'speaking',
        title: '건강 조언 주고받기',
        description: '건강 문제에 대해 조언을 주고받는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['health', 'speaking', 'advice'],
      },
      {
        id: 'A2-W3-A6',
        type: 'reading',
        title: '건강 정보 기사 읽기',
        description: '건강한 생활습관에 대한 기사를 읽습니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['health', 'reading'],
      },
      {
        id: 'A2-W3-A7',
        type: 'writing',
        title: '건강 일기 작성하기',
        description: '자신의 건강 상태와 생활습관을 기록합니다.',
        duration: 30,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['health', 'writing'],
      },
    ],
  },

  // A2 Level - Week 4
  {
    id: 'A2-W4',
    level: 'A2',
    weekNumber: 4,
    title: '쇼핑과 소비',
    description: '쇼핑 상황에서 필요한 의사소통 방법을 배웁니다.',
    objectives: [
      '쇼핑 관련 어휘 확장하기',
      '가정법 과거 (Second Conditional) 학습',
      '가격 흥정과 교환/환불 표현',
      '온라인 쇼핑 용어 이해하기',
    ],
    estimatedTime: 195,
    order: 12,
    activities: [
      {
        id: 'A2-W4-A1',
        type: 'vocabulary',
        title: '쇼핑과 결제 방법',
        description: '다양한 쇼핑 상황과 결제 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['shopping', 'payment', 'vocabulary'],
      },
      {
        id: 'A2-W4-A2',
        type: 'grammar',
        title: '가정법 과거 (Second Conditional)',
        description: '가상의 상황을 표현하는 가정법을 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['conditionals', 'grammar'],
      },
      {
        id: 'A2-W4-A3',
        type: 'listening',
        title: '상점 대화 듣기',
        description: '옷가게에서 점원과 손님의 대화를 듣습니다.',
        duration: 25,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['shopping', 'listening'],
      },
      {
        id: 'A2-W4-A4',
        type: 'speaking',
        title: '교환 및 환불 요청하기',
        description: '제품 교환이나 환불을 요청하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['shopping', 'speaking', 'service'],
      },
      {
        id: 'A2-W4-A5',
        type: 'reading',
        title: '온라인 쇼핑몰 리뷰 읽기',
        description: '제품 리뷰를 읽고 정보를 파악합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: false,
        tags: ['shopping', 'reading', 'review'],
      },
      {
        id: 'A2-W4-A6',
        type: 'writing',
        title: '제품 리뷰 작성하기',
        description: '구매한 제품에 대한 리뷰를 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['shopping', 'writing', 'review'],
      },
      {
        id: 'A2-W4-A7',
        type: 'vocabulary',
        title: '의류와 사이즈 표현',
        description: '옷과 사이즈 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['clothing', 'vocabulary'],
      },
    ],
  },

  // A2 Level - Week 5
  {
    id: 'A2-W5',
    level: 'A2',
    weekNumber: 5,
    title: '직업과 직장생활',
    description: '다양한 직업과 직장에서의 일상을 표현하는 방법을 배웁니다.',
    objectives: [
      '직업과 업무 관련 어휘 익히기',
      '수동태 (Passive Voice) 이해하기',
      '업무 지시와 요청 표현',
      '직장 예절과 이메일 작성',
    ],
    estimatedTime: 205,
    order: 13,
    activities: [
      {
        id: 'A2-W5-A1',
        type: 'vocabulary',
        title: '직업과 직무',
        description: '다양한 직업과 직무 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['jobs', 'work', 'vocabulary'],
      },
      {
        id: 'A2-W5-A2',
        type: 'grammar',
        title: '수동태 현재/과거 시제',
        description: '수동태의 기본 형태와 사용법을 배웁니다.',
        duration: 35,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['passive', 'grammar'],
      },
      {
        id: 'A2-W5-A3',
        type: 'listening',
        title: '회의 대화 듣기',
        description: '직장 회의에서 나누는 대화를 듣고 이해합니다.',
        duration: 30,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['work', 'listening', 'meeting'],
      },
      {
        id: 'A2-W5-A4',
        type: 'grammar',
        title: '간접 화법 (Reported Speech)',
        description: '다른 사람의 말을 전달하는 방법을 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['reported-speech', 'grammar'],
      },
      {
        id: 'A2-W5-A5',
        type: 'speaking',
        title: '업무 보고하기',
        description: '자신의 업무 상황을 보고하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['work', 'speaking'],
      },
      {
        id: 'A2-W5-A6',
        type: 'reading',
        title: '업무 이메일 읽기',
        description: '직장에서 주고받는 이메일을 읽고 이해합니다.',
        duration: 25,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['work', 'reading', 'email'],
      },
      {
        id: 'A2-W5-A7',
        type: 'writing',
        title: '공식 이메일 작성하기',
        description: '격식 있는 업무 이메일을 작성합니다.',
        duration: 30,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['work', 'writing', 'email'],
      },
    ],
  },

  // A2 Level - Week 6
  {
    id: 'A2-W6',
    level: 'A2',
    weekNumber: 6,
    title: '문화와 축제',
    description: '다양한 문화와 축제에 대해 이야기하는 방법을 배웁니다.',
    objectives: [
      '문화와 전통 어휘 확장',
      '관계대명사 (Who, Which, That) 사용',
      '문화 비교와 대조 표현',
      '축제와 행사 묘사하기',
    ],
    estimatedTime: 200,
    order: 14,
    activities: [
      {
        id: 'A2-W6-A1',
        type: 'vocabulary',
        title: '문화와 전통 행사',
        description: '세계 각국의 문화와 전통 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['culture', 'tradition', 'vocabulary'],
      },
      {
        id: 'A2-W6-A2',
        type: 'grammar',
        title: '관계대명사 Who, Which, That',
        description: '사람과 사물을 설명하는 관계대명사를 배웁니다.',
        duration: 35,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['relative-pronouns', 'grammar'],
      },
      {
        id: 'A2-W6-A3',
        type: 'reading',
        title: '세계 축제 안내문 읽기',
        description: '다양한 나라의 축제 안내문을 읽고 이해합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['culture', 'reading', 'festival'],
      },
      {
        id: 'A2-W6-A4',
        type: 'listening',
        title: '문화 소개 방송 듣기',
        description: '문화 프로그램 방송을 듣고 주요 내용을 파악합니다.',
        duration: 30,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['culture', 'listening'],
      },
      {
        id: 'A2-W6-A5',
        type: 'speaking',
        title: '자국 문화 소개하기',
        description: '자신의 나라 문화를 영어로 소개하는 연습을 합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: false,
        tags: ['culture', 'speaking'],
      },
      {
        id: 'A2-W6-A6',
        type: 'writing',
        title: '축제 경험담 작성하기',
        description: '축제나 문화 행사 경험을 글로 작성합니다.',
        duration: 30,
        difficulty: 2,
        order: 6,
        requiredForCompletion: false,
        tags: ['culture', 'writing'],
      },
      {
        id: 'A2-W6-A7',
        type: 'grammar',
        title: 'While vs During 구분',
        description: '시간 표현 while과 during의 차이를 이해합니다.',
        duration: 20,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['time', 'grammar'],
      },
    ],
  },

  // A2 Level - Week 7
  {
    id: 'A2-W7',
    level: 'A2',
    weekNumber: 7,
    title: '환경과 자연',
    description: '환경 문제와 자연에 대해 이야기하는 방법을 배웁니다.',
    objectives: [
      '환경과 날씨 어휘 익히기',
      '조건문 (Zero & First Conditional) 활용',
      '환경 문제 설명하기',
      '의견 제시와 제안하기',
    ],
    estimatedTime: 195,
    order: 15,
    activities: [
      {
        id: 'A2-W7-A1',
        type: 'vocabulary',
        title: '환경 문제와 자연',
        description: '환경과 자연 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 1,
        requiredForCompletion: true,
        tags: ['environment', 'nature', 'vocabulary'],
      },
      {
        id: 'A2-W7-A2',
        type: 'grammar',
        title: '조건문 Zero & First Conditional',
        description: '일반적 사실과 미래 가능성을 표현하는 조건문을 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['conditionals', 'grammar'],
      },
      {
        id: 'A2-W7-A3',
        type: 'reading',
        title: '환경 보호 기사 읽기',
        description: '환경 보호에 관한 뉴스 기사를 읽고 이해합니다.',
        duration: 30,
        difficulty: 2,
        order: 3,
        requiredForCompletion: true,
        tags: ['environment', 'reading'],
      },
      {
        id: 'A2-W7-A4',
        type: 'listening',
        title: '날씨 예보 듣기',
        description: '일기예보를 듣고 주요 정보를 파악합니다.',
        duration: 25,
        difficulty: 2,
        order: 4,
        requiredForCompletion: true,
        tags: ['weather', 'listening'],
      },
      {
        id: 'A2-W7-A5',
        type: 'speaking',
        title: '환경 보호 의견 말하기',
        description: '환경 문제에 대한 자신의 의견을 표현합니다.',
        duration: 30,
        difficulty: 2,
        order: 5,
        requiredForCompletion: true,
        tags: ['environment', 'speaking', 'opinion'],
      },
      {
        id: 'A2-W7-A6',
        type: 'writing',
        title: '환경 보호 제안서 작성',
        description: '환경 보호를 위한 제안서를 작성합니다.',
        duration: 30,
        difficulty: 3,
        order: 6,
        requiredForCompletion: false,
        tags: ['environment', 'writing'],
      },
      {
        id: 'A2-W7-A7',
        type: 'vocabulary',
        title: '재활용과 에너지',
        description: '재활용과 에너지 관련 어휘를 학습합니다.',
        duration: 25,
        difficulty: 2,
        order: 7,
        requiredForCompletion: false,
        tags: ['environment', 'vocabulary'],
      },
    ],
  },

  // A2 Level - Week 8
  {
    id: 'A2-W8',
    level: 'A2',
    weekNumber: 8,
    title: 'A2 레벨 총정리',
    description: 'A2 레벨에서 배운 모든 내용을 복습하고 종합 평가를 진행합니다.',
    objectives: [
      'A2 핵심 문법 총정리',
      'A2 필수 어휘 복습',
      '실전 대화 연습',
      'A2 레벨 마무리 평가',
    ],
    estimatedTime: 180,
    order: 16,
    activities: [
      {
        id: 'A2-W8-A1',
        type: 'grammar',
        title: 'A2 문법 종합 복습',
        description:
          '현재완료, 과거완료, 조건문, 수동태 등 A2 핵심 문법을 복습합니다.',
        duration: 40,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['review', 'grammar'],
      },
      {
        id: 'A2-W8-A2',
        type: 'vocabulary',
        title: 'A2 어휘 총정리',
        description:
          '여행, 취미, 건강, 직업 등 A2 필수 어휘를 복습합니다.',
        duration: 30,
        difficulty: 2,
        order: 2,
        requiredForCompletion: true,
        tags: ['review', 'vocabulary'],
      },
      {
        id: 'A2-W8-A3',
        type: 'listening',
        title: 'A2 종합 듣기 평가',
        description: 'A2 레벨의 다양한 주제를 다룬 듣기 평가를 진행합니다.',
        duration: 30,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['review', 'listening', 'test'],
      },
      {
        id: 'A2-W8-A4',
        type: 'speaking',
        title: 'A2 말하기 종합 평가',
        description: '여러 상황에서 적절히 대화하는 능력을 평가합니다.',
        duration: 30,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['review', 'speaking', 'test'],
      },
      {
        id: 'A2-W8-A5',
        type: 'reading',
        title: 'A2 독해 종합 평가',
        description: '다양한 유형의 글을 읽고 이해하는 능력을 평가합니다.',
        duration: 30,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['review', 'reading', 'test'],
      },
      {
        id: 'A2-W8-A6',
        type: 'writing',
        title: 'A2 작문 종합 평가',
        description: '주어진 주제에 대해 논리적인 글을 작성합니다.',
        duration: 20,
        difficulty: 3,
        order: 6,
        requiredForCompletion: true,
        tags: ['review', 'writing', 'test'],
      },
    ],
  },

  // ==================== B1 레벨 ====================
  // B1 Level - Week 1
  {
    id: 'B1-W1',
    level: 'B1',
    weekNumber: 1,
    title: '미디어와 뉴스',
    description: '다양한 미디어와 뉴스를 이해하고 의견을 표현하는 방법을 배웁니다.',
    objectives: [
      '미디어 관련 어휘 확장',
      '수동태 심화 (모든 시제)',
      '뉴스 기사 읽기와 요약',
      '사실과 의견 구분하기',
    ],
    estimatedTime: 210,
    order: 17,
    activities: [
      {
        id: 'B1-W1-A1',
        type: 'vocabulary',
        title: '미디어와 저널리즘',
        description: '다양한 미디어와 뉴스 관련 전문 용어를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['media', 'news', 'vocabulary'],
      },
      {
        id: 'B1-W1-A2',
        type: 'grammar',
        title: '수동태 모든 시제',
        description:
          '현재, 과거, 미래, 완료 시제의 수동태를 종합적으로 학습합니다.',
        duration: 35,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['passive', 'grammar', 'advanced'],
      },
      {
        id: 'B1-W1-A3',
        type: 'reading',
        title: '뉴스 기사 분석하기',
        description: '실제 뉴스 기사를 읽고 핵심 내용을 파악합니다.',
        duration: 35,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['news', 'reading', 'analysis'],
      },
      {
        id: 'B1-W1-A4',
        type: 'listening',
        title: '뉴스 방송 듣기',
        description: '실제 뉴스 방송을 듣고 주요 사건을 이해합니다.',
        duration: 30,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['news', 'listening'],
      },
      {
        id: 'B1-W1-A5',
        type: 'speaking',
        title: '뉴스 토론하기',
        description: '최근 뉴스에 대한 의견을 논리적으로 표현합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['news', 'speaking', 'debate'],
      },
      {
        id: 'B1-W1-A6',
        type: 'writing',
        title: '뉴스 요약 작성하기',
        description: '뉴스 기사를 읽고 객관적으로 요약합니다.',
        duration: 30,
        difficulty: 3,
        order: 6,
        requiredForCompletion: false,
        tags: ['news', 'writing', 'summary'],
      },
      {
        id: 'B1-W1-A7',
        type: 'grammar',
        title: 'Reported Speech 심화',
        description: '뉴스 보도에 사용되는 간접 화법을 심화 학습합니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['reported-speech', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 2
  {
    id: 'B1-W2',
    level: 'B1',
    weekNumber: 2,
    title: '기술과 혁신',
    description: '현대 기술과 혁신에 대해 토론하는 방법을 배웁니다.',
    objectives: [
      '기술 관련 어휘와 개념 이해',
      '미래 시제 심화 (will, going to, 현재진행)',
      '기술의 장단점 논의하기',
      '예측과 추측 표현하기',
    ],
    estimatedTime: 215,
    order: 18,
    activities: [
      {
        id: 'B1-W2-A1',
        type: 'vocabulary',
        title: '최신 기술 용어',
        description: 'AI, IoT, 클라우드 등 현대 기술 용어를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['technology', 'innovation', 'vocabulary'],
      },
      {
        id: 'B1-W2-A2',
        type: 'grammar',
        title: '미래 표현 비교',
        description:
          'Will, going to, 현재진행형의 미래 표현 차이를 배웁니다.',
        duration: 35,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['future', 'grammar'],
      },
      {
        id: 'B1-W2-A3',
        type: 'reading',
        title: '기술 트렌드 기사 읽기',
        description: '최신 기술 트렌드에 관한 전문 기사를 읽습니다.',
        duration: 35,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['technology', 'reading'],
      },
      {
        id: 'B1-W2-A4',
        type: 'listening',
        title: 'TED 강연 듣기',
        description: '기술 혁신에 관한 영어 강연을 듣고 이해합니다.',
        duration: 35,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['technology', 'listening', 'ted'],
      },
      {
        id: 'B1-W2-A5',
        type: 'speaking',
        title: '기술 토론하기',
        description: '기술의 긍정적/부정적 영향에 대해 토론합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['technology', 'speaking', 'debate'],
      },
      {
        id: 'B1-W2-A6',
        type: 'writing',
        title: '기술 평론 작성하기',
        description:
          '특정 기술에 대한 자신의 견해를 논리적으로 작성합니다.',
        duration: 30,
        difficulty: 3,
        order: 6,
        requiredForCompletion: false,
        tags: ['technology', 'writing', 'opinion'],
      },
      {
        id: 'B1-W2-A7',
        type: 'grammar',
        title: 'Modal Verbs for Speculation',
        description: 'Must, might, could 등 추측 표현을 배웁니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['modals', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 3
  {
    id: 'B1-W3',
    level: 'B1',
    weekNumber: 3,
    title: '교육과 학습',
    description: '교육 시스템과 학습 방법에 대해 논의하는 방법을 배웁니다.',
    objectives: [
      '교육 관련 어휘 확장',
      '가정법 과거완료 (Third Conditional)',
      '교육 방식 비교하기',
      '학습 경험 공유하기',
    ],
    estimatedTime: 205,
    order: 19,
    activities: [
      {
        id: 'B1-W3-A1',
        type: 'vocabulary',
        title: '교육 시스템과 방법론',
        description:
          '다양한 교육 시스템과 학습 방법 관련 어휘를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['education', 'learning', 'vocabulary'],
      },
      {
        id: 'B1-W3-A2',
        type: 'grammar',
        title: '가정법 과거완료 (Third Conditional)',
        description: '과거에 일어나지 않은 일을 가정하는 표현을 배웁니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['conditionals', 'grammar', 'advanced'],
      },
      {
        id: 'B1-W3-A3',
        type: 'reading',
        title: '교육 개혁 기사 읽기',
        description: '교육 제도 개혁에 관한 심화 기사를 읽습니다.',
        duration: 30,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['education', 'reading'],
      },
      {
        id: 'B1-W3-A4',
        type: 'listening',
        title: '교육 전문가 인터뷰 듣기',
        description: '교육 전문가의 인터뷰를 듣고 핵심 내용을 파악합니다.',
        duration: 30,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['education', 'listening', 'interview'],
      },
      {
        id: 'B1-W3-A5',
        type: 'speaking',
        title: '학습 방법 토론하기',
        description: '효과적인 학습 방법에 대해 의견을 나눕니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['education', 'speaking', 'debate'],
      },
      {
        id: 'B1-W3-A6',
        type: 'writing',
        title: '교육 제안서 작성하기',
        description: '교육 개선을 위한 제안서를 논리적으로 작성합니다.',
        duration: 30,
        difficulty: 3,
        order: 6,
        requiredForCompletion: false,
        tags: ['education', 'writing', 'proposal'],
      },
      {
        id: 'B1-W3-A7',
        type: 'grammar',
        title: 'I wish / If only 표현',
        description: '아쉬움과 후회를 표현하는 방법을 배웁니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['wish', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 4
  {
    id: 'B1-W4',
    level: 'B1',
    weekNumber: 4,
    title: '사회 문제와 해결책',
    description:
      '다양한 사회 문제를 이해하고 해결책을 제시하는 방법을 배웁니다.',
    objectives: [
      '사회 문제 관련 어휘 익히기',
      '인과관계 표현 (Cause and Effect)',
      '문제와 해결책 구조화하기',
      '설득력 있는 주장 전개하기',
    ],
    estimatedTime: 210,
    order: 20,
    activities: [
      {
        id: 'B1-W4-A1',
        type: 'vocabulary',
        title: '사회 문제와 공공정책',
        description:
          '빈곤, 불평등, 범죄 등 사회 문제 관련 어휘를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['society', 'issues', 'vocabulary'],
      },
      {
        id: 'B1-W4-A2',
        type: 'grammar',
        title: 'Cause and Effect Structures',
        description:
          'Because of, due to, as a result 등 인과관계 표현을 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['cause-effect', 'grammar'],
      },
      {
        id: 'B1-W4-A3',
        type: 'reading',
        title: '사회 이슈 분석 기사',
        description: '복잡한 사회 문제를 다룬 기사를 읽고 분석합니다.',
        duration: 35,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['society', 'reading', 'analysis'],
      },
      {
        id: 'B1-W4-A4',
        type: 'listening',
        title: '사회 토론 프로그램 듣기',
        description:
          '사회 문제에 대한 토론을 듣고 다양한 관점을 이해합니다.',
        duration: 35,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['society', 'listening', 'debate'],
      },
      {
        id: 'B1-W4-A5',
        type: 'speaking',
        title: '해결책 제시하기',
        description: '사회 문제에 대한 실질적인 해결책을 제시합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['society', 'speaking', 'solution'],
      },
      {
        id: 'B1-W4-A6',
        type: 'writing',
        title: '의견 에세이 작성하기',
        description:
          '사회 문제에 대한 의견을 논리적 에세이로 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['society', 'writing', 'essay'],
      },
      {
        id: 'B1-W4-A7',
        type: 'grammar',
        title: 'Linking Words Advanced',
        description:
          'Furthermore, however, nevertheless 등 고급 연결어를 배웁니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['linking-words', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 5
  {
    id: 'B1-W5',
    level: 'B1',
    weekNumber: 5,
    title: '비즈니스와 경제',
    description: '비즈니스 환경과 경제 개념을 이해하고 표현하는 방법을 배웁니다.',
    objectives: [
      '비즈니스 전문 용어 익히기',
      '관계부사절 (Where, When, Why)',
      '비즈니스 프레젠테이션 기법',
      '경제 뉴스 이해하기',
    ],
    estimatedTime: 215,
    order: 21,
    activities: [
      {
        id: 'B1-W5-A1',
        type: 'vocabulary',
        title: '비즈니스와 금융 용어',
        description: '경영, 마케팅, 금융 관련 전문 용어를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['business', 'finance', 'vocabulary'],
      },
      {
        id: 'B1-W5-A2',
        type: 'grammar',
        title: '관계부사 Where, When, Why',
        description: '장소, 시간, 이유를 설명하는 관계부사를 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['relative-adverbs', 'grammar'],
      },
      {
        id: 'B1-W5-A3',
        type: 'reading',
        title: '경제 뉴스 읽기',
        description: '경제 동향과 시장 분석 기사를 읽고 이해합니다.',
        duration: 35,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['business', 'reading', 'economics'],
      },
      {
        id: 'B1-W5-A4',
        type: 'listening',
        title: '비즈니스 프레젠테이션 듣기',
        description: '실제 비즈니스 프레젠테이션을 듣고 핵심을 파악합니다.',
        duration: 35,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['business', 'listening', 'presentation'],
      },
      {
        id: 'B1-W5-A5',
        type: 'speaking',
        title: '비즈니스 미팅 참여하기',
        description: '비즈니스 미팅에서 효과적으로 의견을 제시합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['business', 'speaking', 'meeting'],
      },
      {
        id: 'B1-W5-A6',
        type: 'writing',
        title: '비즈니스 보고서 작성하기',
        description: '간단한 비즈니스 보고서를 전문적으로 작성합니다.',
        duration: 35,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['business', 'writing', 'report'],
      },
      {
        id: 'B1-W5-A7',
        type: 'grammar',
        title: 'Formal vs Informal Language',
        description: '격식체와 비격식체 언어의 차이를 이해합니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['formality', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 6
  {
    id: 'B1-W6',
    level: 'B1',
    weekNumber: 6,
    title: '예술과 문화',
    description: '예술 작품과 문화 현상을 분석하고 감상을 표현하는 방법을 배웁니다.',
    objectives: [
      '예술 비평 어휘 확장',
      '분사구문 (Participle Clauses)',
      '작품 분석과 감상 표현',
      '문화적 맥락 이해하기',
    ],
    estimatedTime: 205,
    order: 22,
    activities: [
      {
        id: 'B1-W6-A1',
        type: 'vocabulary',
        title: '예술과 미학 용어',
        description: '미술, 음악, 문학 등 예술 분야 어휘를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['art', 'culture', 'vocabulary'],
      },
      {
        id: 'B1-W6-A2',
        type: 'grammar',
        title: '분사구문 (Participle Clauses)',
        description: '현재분사와 과거분사를 활용한 문장 축약을 배웁니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['participles', 'grammar', 'advanced'],
      },
      {
        id: 'B1-W6-A3',
        type: 'reading',
        title: '예술 비평 읽기',
        description: '전문적인 예술 비평문을 읽고 이해합니다.',
        duration: 30,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['art', 'reading', 'criticism'],
      },
      {
        id: 'B1-W6-A4',
        type: 'listening',
        title: '갤러리 오디오 가이드 듣기',
        description: '미술관 오디오 가이드를 듣고 작품을 이해합니다.',
        duration: 30,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['art', 'listening', 'museum'],
      },
      {
        id: 'B1-W6-A5',
        type: 'speaking',
        title: '예술 작품 감상 말하기',
        description: '예술 작품에 대한 개인적 감상을 표현합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['art', 'speaking', 'opinion'],
      },
      {
        id: 'B1-W6-A6',
        type: 'writing',
        title: '전시회 리뷰 작성하기',
        description: '전시회나 공연에 대한 리뷰를 작성합니다.',
        duration: 30,
        difficulty: 3,
        order: 6,
        requiredForCompletion: false,
        tags: ['art', 'writing', 'review'],
      },
      {
        id: 'B1-W6-A7',
        type: 'grammar',
        title: 'Adjective Order',
        description: '여러 형용사를 올바른 순서로 배열하는 방법을 배웁니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['adjectives', 'grammar'],
      },
    ],
  },

  // B1 Level - Week 7
  {
    id: 'B1-W7',
    level: 'B1',
    weekNumber: 7,
    title: '과학과 발견',
    description: '과학적 개념과 발견을 이해하고 설명하는 방법을 배웁니다.',
    objectives: [
      '과학 용어와 개념 이해',
      '양보절 (Although, Despite, However)',
      '과학적 과정 설명하기',
      '가설과 결론 표현하기',
    ],
    estimatedTime: 210,
    order: 23,
    activities: [
      {
        id: 'B1-W7-A1',
        type: 'vocabulary',
        title: '과학 분야별 용어',
        description: '물리, 화학, 생물 등 기초 과학 용어를 학습합니다.',
        duration: 30,
        difficulty: 3,
        order: 1,
        requiredForCompletion: true,
        tags: ['science', 'vocabulary'],
      },
      {
        id: 'B1-W7-A2',
        type: 'grammar',
        title: '양보절 (Concession)',
        description: 'Although, despite, however 등 양보 표현을 배웁니다.',
        duration: 30,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['concession', 'grammar'],
      },
      {
        id: 'B1-W7-A3',
        type: 'reading',
        title: '과학 저널 기사 읽기',
        description: '대중적인 과학 저널 기사를 읽고 이해합니다.',
        duration: 35,
        difficulty: 3,
        order: 3,
        requiredForCompletion: true,
        tags: ['science', 'reading'],
      },
      {
        id: 'B1-W7-A4',
        type: 'listening',
        title: '과학 다큐멘터리 듣기',
        description: '과학 다큐멘터리를 보고 핵심 내용을 파악합니다.',
        duration: 35,
        difficulty: 3,
        order: 4,
        requiredForCompletion: true,
        tags: ['science', 'listening', 'documentary'],
      },
      {
        id: 'B1-W7-A5',
        type: 'speaking',
        title: '과학 실험 설명하기',
        description: '과학 실험 과정과 결과를 논리적으로 설명합니다.',
        duration: 35,
        difficulty: 3,
        order: 5,
        requiredForCompletion: true,
        tags: ['science', 'speaking', 'experiment'],
      },
      {
        id: 'B1-W7-A6',
        type: 'writing',
        title: '과학 보고서 작성하기',
        description: '간단한 과학 실험 보고서를 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['science', 'writing', 'report'],
      },
      {
        id: 'B1-W7-A7',
        type: 'grammar',
        title: 'The Passive in Scientific Writing',
        description: '과학 글쓰기에서 수동태 활용법을 배웁니다.',
        duration: 15,
        difficulty: 3,
        order: 7,
        requiredForCompletion: false,
        tags: ['passive', 'grammar', 'science'],
      },
    ],
  },

  // B1 Level - Week 8
  {
    id: 'B1-W8',
    level: 'B1',
    weekNumber: 8,
    title: 'B1 레벨 총정리',
    description: 'B1 레벨에서 배운 모든 내용을 복습하고 종합 평가를 진행합니다.',
    objectives: [
      'B1 고급 문법 총정리',
      'B1 전문 어휘 복습',
      '논리적 글쓰기 완성',
      'B1 레벨 마무리 평가',
    ],
    estimatedTime: 200,
    order: 24,
    activities: [
      {
        id: 'B1-W8-A1',
        type: 'grammar',
        title: 'B1 문법 종합 복습',
        description:
          '가정법, 분사구문, 관계절 등 B1 고급 문법을 복습합니다.',
        duration: 45,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['review', 'grammar'],
      },
      {
        id: 'B1-W8-A2',
        type: 'vocabulary',
        title: 'B1 전문 어휘 총정리',
        description:
          '미디어, 기술, 비즈니스, 과학 등 전문 어휘를 복습합니다.',
        duration: 35,
        difficulty: 3,
        order: 2,
        requiredForCompletion: true,
        tags: ['review', 'vocabulary'],
      },
      {
        id: 'B1-W8-A3',
        type: 'reading',
        title: 'B1 독해 종합 평가',
        description: '다양한 주제의 고급 텍스트를 읽고 이해합니다.',
        duration: 35,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['review', 'reading', 'test'],
      },
      {
        id: 'B1-W8-A4',
        type: 'listening',
        title: 'B1 듣기 종합 평가',
        description: '강연, 토론, 뉴스 등 다양한 듣기 자료를 이해합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['review', 'listening', 'test'],
      },
      {
        id: 'B1-W8-A5',
        type: 'speaking',
        title: 'B1 말하기 종합 평가',
        description: '복잡한 주제에 대해 논리적으로 의견을 표현합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['review', 'speaking', 'test'],
      },
      {
        id: 'B1-W8-A6',
        type: 'writing',
        title: 'B1 작문 종합 평가',
        description: '논리적이고 설득력 있는 에세이를 작성합니다.',
        duration: 25,
        difficulty: 4,
        order: 6,
        requiredForCompletion: true,
        tags: ['review', 'writing', 'test'],
      },
    ],
  },

  // ===== B2 Level (Advanced) =====
  {
    id: 'B2-W1',
    level: 'B2',
    weekNumber: 1,
    title: '글로벌 이슈와 국제 관계',
    description: '세계적인 문제들과 국제 정치에 대해 심층적으로 논의합니다.',
    objectives: [
      '국제 정치 용어 익히기',
      '복잡한 시사 문제 이해하기',
      '다양한 관점에서 분석하기',
      '설득력 있는 논증 구성하기',
    ],
    estimatedTime: 190,
    order: 25,
    activities: [
      {
        id: 'B2-W1-A1',
        type: 'vocabulary',
        title: '국제 관계 전문 용어',
        description: 'diplomacy, sovereignty, treaty, sanction 등 국제 정치 관련 고급 어휘를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['politics', 'vocabulary', 'advanced'],
      },
      {
        id: 'B2-W1-A2',
        type: 'reading',
        title: '국제 뉴스 분석',
        description: 'The Economist, BBC 등의 국제 뉴스를 읽고 비판적으로 분석합니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['news', 'analysis', 'critical-thinking'],
      },
      {
        id: 'B2-W1-A3',
        type: 'listening',
        title: 'UN 연설문 듣기',
        description: '유엔 연설문과 국제 회의 내용을 듣고 핵심 논점을 파악합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['speech', 'politics', 'comprehension'],
      },
      {
        id: 'B2-W1-A4',
        type: 'speaking',
        title: '국제 이슈 토론',
        description: '기후변화, 난민 문제 등 글로벌 이슈에 대해 토론합니다.',
        duration: 35,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['debate', 'discussion', 'global-issues'],
      },
      {
        id: 'B2-W1-A5',
        type: 'writing',
        title: '논평 작성',
        description: '국제 이슈에 대한 논평문을 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['opinion', 'writing', 'analysis'],
      },
      {
        id: 'B2-W1-A6',
        type: 'grammar',
        title: '고급 수동태와 보고 구문',
        description: 'It is said that, It is believed that 등 고급 보고 구문을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['passive-voice', 'reported-speech', 'advanced-grammar'],
      },
    ],
  },
  {
    id: 'B2-W2',
    level: 'B2',
    weekNumber: 2,
    title: '철학과 윤리',
    description: '철학적 사고와 윤리적 딜레마에 대해 탐구합니다.',
    objectives: [
      '철학 용어와 개념 이해하기',
      '윤리적 딜레마 분석하기',
      '논리적 주장 전개하기',
      '추상적 개념 표현하기',
    ],
    estimatedTime: 185,
    order: 26,
    activities: [
      {
        id: 'B2-W2-A1',
        type: 'vocabulary',
        title: '철학 및 윤리 용어',
        description: 'morality, ethics, dilemma, virtue 등 철학과 윤리 관련 어휘를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['philosophy', 'ethics', 'vocabulary'],
      },
      {
        id: 'B2-W2-A2',
        type: 'reading',
        title: '철학 에세이 읽기',
        description: '유명 철학자들의 에세이를 읽고 핵심 논지를 파악합니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['philosophy', 'essay', 'comprehension'],
      },
      {
        id: 'B2-W2-A3',
        type: 'listening',
        title: '윤리 강의 듣기',
        description: '윤리학 강의를 듣고 다양한 윤리 이론을 이해합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['ethics', 'lecture', 'theory'],
      },
      {
        id: 'B2-W2-A4',
        type: 'speaking',
        title: '윤리적 딜레마 토론',
        description: '트롤리 문제 등 윤리적 딜레마에 대해 토론합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['debate', 'ethics', 'dilemma'],
      },
      {
        id: 'B2-W2-A5',
        type: 'writing',
        title: '철학적 에세이 작성',
        description: '특정 철학 주제에 대한 에세이를 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['essay', 'philosophy', 'writing'],
      },
      {
        id: 'B2-W2-A6',
        type: 'grammar',
        title: '가정법과 조건문 심화',
        description: '복잡한 가정법 구문과 혼합 조건문을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['conditionals', 'subjunctive', 'advanced-grammar'],
      },
    ],
  },
  {
    id: 'B2-W3',
    level: 'B2',
    weekNumber: 3,
    title: '학술 연구와 방법론',
    description: '학술 논문의 구조와 연구 방법론을 이해합니다.',
    objectives: [
      '학술 논문 읽기',
      '연구 방법론 이해하기',
      '비판적 평가하기',
      '학술적 글쓰기 연습하기',
    ],
    estimatedTime: 185,
    order: 27,
    activities: [
      {
        id: 'B2-W3-A1',
        type: 'vocabulary',
        title: '학술 연구 용어',
        description: 'hypothesis, methodology, empirical, correlation 등 연구 관련 어휘를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['research', 'academic', 'vocabulary'],
      },
      {
        id: 'B2-W3-A2',
        type: 'reading',
        title: '학술 논문 분석',
        description: '학술 논문의 구조와 논리를 분석합니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['academic', 'paper', 'analysis'],
      },
      {
        id: 'B2-W3-A3',
        type: 'listening',
        title: '학술 발표 듣기',
        description: 'TED 강연과 학술 발표를 듣고 핵심 내용을 파악합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['presentation', 'academic', 'comprehension'],
      },
      {
        id: 'B2-W3-A4',
        type: 'speaking',
        title: '연구 발표 연습',
        description: '자신의 연구나 관심 주제를 학술적으로 발표합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['presentation', 'academic', 'speaking'],
      },
      {
        id: 'B2-W3-A5',
        type: 'writing',
        title: '연구 초록 작성',
        description: '학술 논문의 초록(abstract)을 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['abstract', 'academic-writing', 'research'],
      },
      {
        id: 'B2-W3-A6',
        type: 'grammar',
        title: '학술적 표현 구문',
        description: 'Nominalization, hedging 등 학술적 표현 기법을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['academic-style', 'hedging', 'nominalization'],
      },
    ],
  },
  {
    id: 'B2-W4',
    level: 'B2',
    weekNumber: 4,
    title: '심리학과 인간 행동',
    description: '심리학의 주요 개념과 인간 행동의 메커니즘을 탐구합니다.',
    objectives: [
      '심리학 주요 개념 이해하기',
      '행동 패턴 분석하기',
      '심리학 연구 결과 해석하기',
      '인간 행동에 대해 토론하기',
    ],
    estimatedTime: 185,
    order: 28,
    activities: [
      {
        id: 'B2-W4-A1',
        type: 'vocabulary',
        title: '심리학 전문 용어',
        description: 'cognition, perception, motivation, behavior 등 심리학 용어를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['psychology', 'vocabulary', 'science'],
      },
      {
        id: 'B2-W4-A2',
        type: 'reading',
        title: '심리학 논문 읽기',
        description: '심리학 실험과 연구 결과를 다룬 논문을 읽습니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['psychology', 'research', 'comprehension'],
      },
      {
        id: 'B2-W4-A3',
        type: 'listening',
        title: '심리학 다큐멘터리',
        description: '인간 행동과 심리에 관한 다큐멘터리를 시청합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['documentary', 'psychology', 'comprehension'],
      },
      {
        id: 'B2-W4-A4',
        type: 'speaking',
        title: '심리학 이론 토론',
        description: '다양한 심리학 이론에 대해 토론하고 평가합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['debate', 'psychology', 'theory'],
      },
      {
        id: 'B2-W4-A5',
        type: 'writing',
        title: '행동 분석 보고서',
        description: '특정 행동 패턴을 관찰하고 분석한 보고서를 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['report', 'analysis', 'psychology'],
      },
      {
        id: 'B2-W4-A6',
        type: 'grammar',
        title: '원인과 결과 표현',
        description: 'Due to, owing to, as a result of 등 원인과 결과를 나타내는 고급 표현을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['cause-effect', 'linking-words', 'advanced-grammar'],
      },
    ],
  },
  {
    id: 'B2-W5',
    level: 'B2',
    weekNumber: 5,
    title: '경제학과 금융',
    description: '경제 이론과 금융 시스템에 대해 심층적으로 학습합니다.',
    objectives: [
      '경제 및 금융 용어 익히기',
      '경제 뉴스 이해하기',
      '경제 현상 분석하기',
      '투자와 금융에 대해 논의하기',
    ],
    estimatedTime: 185,
    order: 29,
    activities: [
      {
        id: 'B2-W5-A1',
        type: 'vocabulary',
        title: '경제 및 금융 용어',
        description: 'inflation, recession, equity, bond, portfolio 등 경제 금융 용어를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['economics', 'finance', 'vocabulary'],
      },
      {
        id: 'B2-W5-A2',
        type: 'reading',
        title: '경제 분석 기사',
        description: 'Financial Times, WSJ 등의 경제 분석 기사를 읽습니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['economics', 'news', 'analysis'],
      },
      {
        id: 'B2-W5-A3',
        type: 'listening',
        title: '경제 전문가 인터뷰',
        description: '경제학자와 금융 전문가의 인터뷰를 듣고 이해합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['interview', 'economics', 'expert'],
      },
      {
        id: 'B2-W5-A4',
        type: 'speaking',
        title: '경제 정책 토론',
        description: '금리, 세금 등 경제 정책에 대해 토론합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['debate', 'economics', 'policy'],
      },
      {
        id: 'B2-W5-A5',
        type: 'writing',
        title: '경제 동향 분석',
        description: '최근 경제 동향을 분석한 보고서를 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['report', 'economics', 'analysis'],
      },
      {
        id: 'B2-W5-A6',
        type: 'grammar',
        title: '비교와 대조 표현',
        description: 'Whereas, in contrast to, compared with 등 비교 대조 표현을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['comparison', 'contrast', 'advanced-grammar'],
      },
    ],
  },
  {
    id: 'B2-W6',
    level: 'B2',
    weekNumber: 6,
    title: '문학과 비평',
    description: '문학 작품을 읽고 비평하는 능력을 기릅니다.',
    objectives: [
      '문학 용어와 기법 이해하기',
      '소설과 시 분석하기',
      '문학 비평 작성하기',
      '작가의 의도 파악하기',
    ],
    estimatedTime: 185,
    order: 30,
    activities: [
      {
        id: 'B2-W6-A1',
        type: 'vocabulary',
        title: '문학 비평 용어',
        description: 'metaphor, symbolism, irony, theme, narrative 등 문학 용어를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['literature', 'vocabulary', 'criticism'],
      },
      {
        id: 'B2-W6-A2',
        type: 'reading',
        title: '단편 소설 분석',
        description: '영미 단편 소설을 읽고 주제와 문학적 기법을 분석합니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['literature', 'fiction', 'analysis'],
      },
      {
        id: 'B2-W6-A3',
        type: 'listening',
        title: '시 낭독과 해설',
        description: '유명 시인의 작품 낭독과 해설을 듣습니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['poetry', 'literature', 'interpretation'],
      },
      {
        id: 'B2-W6-A4',
        type: 'speaking',
        title: '문학 작품 토론',
        description: '읽은 작품의 주제와 의미에 대해 토론합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['debate', 'literature', 'interpretation'],
      },
      {
        id: 'B2-W6-A5',
        type: 'writing',
        title: '문학 비평 작성',
        description: '특정 작품에 대한 문학 비평문을 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['criticism', 'literature', 'writing'],
      },
      {
        id: 'B2-W6-A6',
        type: 'grammar',
        title: '서술 시제와 관점',
        description: '과거 서술, 현재 서술 등 다양한 서술 기법을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['narrative', 'tense', 'point-of-view'],
      },
    ],
  },
  {
    id: 'B2-W7',
    level: 'B2',
    weekNumber: 7,
    title: '고급 의사소통 전략',
    description: '복잡한 상황에서의 효과적인 의사소통 기술을 연마합니다.',
    objectives: [
      '설득과 협상 기술 익히기',
      '프레젠테이션 능력 향상하기',
      '비언어적 의사소통 이해하기',
      '문화 간 의사소통 연습하기',
    ],
    estimatedTime: 185,
    order: 31,
    activities: [
      {
        id: 'B2-W7-A1',
        type: 'vocabulary',
        title: '설득과 협상 표현',
        description: 'persuasion, negotiation, compromise, consensus 등 의사소통 전략 용어를 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['communication', 'negotiation', 'vocabulary'],
      },
      {
        id: 'B2-W7-A2',
        type: 'reading',
        title: '협상 사례 연구',
        description: '성공적인 협상 사례를 읽고 전략을 분석합니다.',
        duration: 35,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['negotiation', 'case-study', 'strategy'],
      },
      {
        id: 'B2-W7-A3',
        type: 'listening',
        title: '전문가 프레젠테이션',
        description: 'TED 강연과 전문가 프레젠테이션을 듣고 기법을 분석합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['presentation', 'public-speaking', 'technique'],
      },
      {
        id: 'B2-W7-A4',
        type: 'speaking',
        title: '협상 시뮬레이션',
        description: '비즈니스 협상 상황을 시뮬레이션합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['negotiation', 'simulation', 'role-play'],
      },
      {
        id: 'B2-W7-A5',
        type: 'writing',
        title: '설득적 제안서 작성',
        description: '프로젝트 제안서나 비즈니스 제안서를 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['proposal', 'persuasion', 'business-writing'],
      },
      {
        id: 'B2-W7-A6',
        type: 'grammar',
        title: '강조와 완곡 표현',
        description: 'Emphasis, euphemism 등 뉘앙스 조절 기법을 학습합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: false,
        tags: ['emphasis', 'euphemism', 'nuance'],
      },
    ],
  },
  {
    id: 'B2-W8',
    level: 'B2',
    weekNumber: 8,
    title: 'B2 레벨 총정리',
    description: 'B2 레벨에서 학습한 모든 내용을 종합적으로 복습하고 평가합니다.',
    objectives: [
      'B2 레벨 전체 내용 복습',
      '고급 언어 능력 종합 평가',
      '실전 활용 능력 점검',
      '다음 단계 준비',
    ],
    estimatedTime: 180,
    order: 32,
    activities: [
      {
        id: 'B2-W8-A1',
        type: 'vocabulary',
        title: 'B2 어휘 종합 평가',
        description: '글로벌 이슈, 철학, 학술, 심리, 경제, 문학 등 모든 영역의 고급 어휘를 복습합니다.',
        duration: 30,
        difficulty: 4,
        order: 1,
        requiredForCompletion: true,
        tags: ['review', 'vocabulary', 'test'],
      },
      {
        id: 'B2-W8-A2',
        type: 'grammar',
        title: 'B2 문법 종합 평가',
        description: '수동태, 가정법, 학술적 표현 등 모든 고급 문법을 복습합니다.',
        duration: 30,
        difficulty: 4,
        order: 2,
        requiredForCompletion: true,
        tags: ['review', 'grammar', 'test'],
      },
      {
        id: 'B2-W8-A3',
        type: 'reading',
        title: 'B2 독해 종합 평가',
        description: '학술 논문, 문학 작품, 경제 기사 등 다양한 고급 텍스트를 읽고 분석합니다.',
        duration: 30,
        difficulty: 4,
        order: 3,
        requiredForCompletion: true,
        tags: ['review', 'reading', 'test'],
      },
      {
        id: 'B2-W8-A4',
        type: 'listening',
        title: 'B2 듣기 종합 평가',
        description: '학술 강연, 전문가 인터뷰, 다큐멘터리 등 고급 듣기 자료를 이해합니다.',
        duration: 30,
        difficulty: 4,
        order: 4,
        requiredForCompletion: true,
        tags: ['review', 'listening', 'test'],
      },
      {
        id: 'B2-W8-A5',
        type: 'speaking',
        title: 'B2 말하기 종합 평가',
        description: '복잡한 주제에 대해 설득력 있게 논증하고 토론합니다.',
        duration: 30,
        difficulty: 4,
        order: 5,
        requiredForCompletion: true,
        tags: ['review', 'speaking', 'test'],
      },
      {
        id: 'B2-W8-A6',
        type: 'writing',
        title: 'B2 작문 종합 평가',
        description: '학술적이고 전문적인 글을 작성합니다.',
        duration: 30,
        difficulty: 4,
        order: 6,
        requiredForCompletion: true,
        tags: ['review', 'writing', 'test'],
      },
    ],
  },
];

// 레벨별 주차 필터링 헬퍼
export const getWeeksByLevel = (level: string) => {
  return curriculumData.filter((week) => week.level === level);
};

// 특정 주차 찾기
export const getWeekById = (weekId: string) => {
  return curriculumData.find((week) => week.id === weekId);
};

// 다음 주차 찾기
export const getNextWeek = (currentWeekId: string) => {
  const currentIndex = curriculumData.findIndex(
    (week) => week.id === currentWeekId
  );
  if (currentIndex === -1 || currentIndex === curriculumData.length - 1) {
    return null;
  }
  return curriculumData[currentIndex + 1];
};

// 이전 주차 찾기
export const getPreviousWeek = (currentWeekId: string) => {
  const currentIndex = curriculumData.findIndex(
    (week) => week.id === currentWeekId
  );
  if (currentIndex <= 0) {
    return null;
  }
  return curriculumData[currentIndex - 1];
};
